datasets:
    train:
        target: example.objects.MyDataset
        params:
            n_classes: 5
    val:
        target: example.objects.MyDataset
        params:
            n_classes: 5
model:
    target: example.objects.MyModel
    params:
        n_classes: 5
    input_map: { "x": ["batch", 1] }
loss_fn:
    target: torch.nn.CrossEntropyLoss
    input_map: { "input": ["model_out"], "target": ["batch", 0] }
optimizer:
    target: torch.optim.Adam
    params:
        lr: 3.0e-4
train:
    dataset: train
    loader_params:
        shuffle: True
        batch_size: 32
    tollerance: 10
val:
    dataset: val
    loader_params:
        batch_size: 32
epochs: 100
